/**
 * 前端路由路径常量与旧路径重定向表。
 * 修改路径时请同步更新 docs/ROUTES_STRUCTURE.md，并保持 legacy 兼容项。
 */
export const ROUTES = {
  MEMBER: {
    ROOT: "/",
    LOGIN_LEGACY: "/member/login",
    HOME: "/member",
    DASHBOARD: "/member/dashboard",
    SPIN: "/member/spin",
    POINTS: "/member/points",
    INVITE: "/member/invite",
    SETTINGS: "/member/settings",
    WALLET: "/member/wallet",
    /** 会员订单（与设置页同源 API） */
    ORDERS: "/member/orders",
    /** 首页任务「首笔交易」：联系客服（与悬浮客服同源坐席列表） */
    TRADE_CONTACT: "/member/trade-contact",
    PROFILE: "/member/profile",
    NOTIFICATIONS: "/member/notifications",
    ONBOARDING: "/member/onboarding",
    /** 首次登录 / 管理员重置密码后强制改密（完成前不可进业务页） */
    FIRST_PASSWORD: "/member/first-password",
    /** 推广落地：?ref= 与邀请码，重定向至 /invite/:code */
    REGISTER: "/member/register",
    INVITE_LANDING: "/invite/:code",
  },
  STAFF: {
    LOGIN: "/staff/login",
    SIGNUP: "/staff/signup",
    ROOT: "/staff",
    ORDERS: "/staff/orders",
    MEMBERS: "/staff/members",
    EMPLOYEES: "/staff/employees",
    REPORTS: "/staff/reports",
    SETTINGS: "/staff/settings",
    MEMBER_MANAGEMENT: "/staff/member-management",
    EXCHANGE_RATE: "/staff/exchange-rate",
    CUSTOMER_QUERY: "/staff/customer-query",
    MERCHANTS: "/staff/merchants",
    MERCHANT_SETTLEMENT: "/staff/merchant-settlement",
    ACTIVITY_REPORTS: "/staff/activity-reports",
    MEMBER_ACTIVITY: "/staff/member-activity",
    OPERATION_LOGS: "/staff/operation-logs",
    LOGIN_LOGS: "/staff/login-logs",
    AUDIT_CENTER: "/staff/audit-center",
    PENDING: "/staff/pending",
    KNOWLEDGE: "/staff/knowledge",
    TASKS_DASHBOARD: "/staff/tasks/dashboard",
    TASKS_SETTINGS: "/staff/tasks/settings",
    TASKS_HISTORY: "/staff/tasks/history",
    TASKS_POSTERS: "/staff/tasks/posters",
    TASKS_PHONE_EXTRACT: "/staff/tasks/phone-extract",
    MEMBER_PROMOTION: "/staff/member-promotion",
    MEMBER_PORTAL: "/staff/member-portal",
    ADMIN_ROOT: "/staff/admin",
    ADMIN_TENANTS: "/staff/admin/tenants",
    ADMIN_TENANT_VIEW: "/staff/admin/tenant-view",
    ADMIN_SETTINGS: "/staff/admin/settings",
    ADMIN_SETTINGS_TAB: "/staff/admin/settings/:tab",
    ADMIN_SETTINGS_DEFAULT: "/staff/admin/settings/ip-control",
  },
  PUBLIC_RATES: "/public-rates",
  NOT_FOUND: "/404",
} as const;

/** 历史员工端路径 → 当前 /staff/* 规范路径（保留书签与外链兼容） */
export const LEGACY_STAFF_REDIRECTS: Array<{ from: string; to: string }> = [
  { from: "/login", to: ROUTES.STAFF.LOGIN },
  { from: "/signup", to: ROUTES.STAFF.SIGNUP },
  { from: "/orders", to: ROUTES.STAFF.ORDERS },
  { from: "/members", to: ROUTES.STAFF.MEMBERS },
  { from: "/employees", to: ROUTES.STAFF.EMPLOYEES },
  { from: "/reports", to: ROUTES.STAFF.REPORTS },
  { from: "/settings", to: ROUTES.STAFF.SETTINGS },
  { from: "/exchange-rate", to: ROUTES.STAFF.EXCHANGE_RATE },
  { from: "/customer-query", to: ROUTES.STAFF.CUSTOMER_QUERY },
  { from: "/merchants", to: ROUTES.STAFF.MERCHANTS },
  { from: "/merchant-settlement", to: ROUTES.STAFF.MERCHANT_SETTLEMENT },
  { from: "/activity-reports", to: ROUTES.STAFF.ACTIVITY_REPORTS },
  { from: "/member-activity", to: ROUTES.STAFF.MEMBER_ACTIVITY },
  { from: "/member-promotion", to: ROUTES.STAFF.MEMBER_PROMOTION },
  { from: "/operation-logs", to: ROUTES.STAFF.OPERATION_LOGS },
  { from: "/login-logs", to: ROUTES.STAFF.LOGIN_LOGS },
  { from: "/audit-center", to: ROUTES.STAFF.AUDIT_CENTER },
  { from: "/pending-authorization", to: ROUTES.STAFF.PENDING },
  { from: "/knowledge", to: ROUTES.STAFF.KNOWLEDGE },
  { from: "/company-management", to: ROUTES.STAFF.ADMIN_TENANTS },
  { from: "/platform-tenant-view", to: ROUTES.STAFF.ADMIN_TENANT_VIEW },
  { from: "/platform-settings", to: ROUTES.STAFF.ADMIN_SETTINGS },
  { from: "/tasks/dashboard", to: ROUTES.STAFF.TASKS_DASHBOARD },
  { from: "/tasks/settings", to: ROUTES.STAFF.TASKS_SETTINGS },
  { from: "/tasks/history", to: ROUTES.STAFF.TASKS_HISTORY },
  { from: "/tasks/posters", to: ROUTES.STAFF.TASKS_POSTERS },
  { from: "/tasks/phone-extract", to: ROUTES.STAFF.TASKS_PHONE_EXTRACT },
  { from: "/admin", to: ROUTES.STAFF.ADMIN_ROOT },
  { from: "/admin/tenants", to: ROUTES.STAFF.ADMIN_TENANTS },
  { from: "/admin/tenant-view", to: ROUTES.STAFF.ADMIN_TENANT_VIEW },
  { from: "/admin/settings", to: ROUTES.STAFF.ADMIN_SETTINGS },
];
