/**
 * 可导出表配置
 */

import type { TableConfig } from './types';

export const EXPORTABLE_TABLES: TableConfig[] = [
  {
    tableName: 'members',
    displayName: '会员管理',
    displayNameEn: 'Members',
    /** 列顺序与员工端会员列表表头一致（MemberManagementContent） */
    columns: [
      { key: 'phone_number', label: '电话号码', labelEn: 'Phone Number' },
      { key: 'member_code', label: '会员编号', labelEn: 'Member Code' },
      { key: 'nickname', label: '用户名称', labelEn: 'Display name' },
      { key: 'created_at', label: '注册时间', labelEn: 'Registered' },
      { key: 'referrer_phone', label: '推荐人电话', labelEn: 'Referrer phone' },
      { key: 'referrer_member_code', label: '推荐人编号', labelEn: 'Referrer code' },
      { key: 'member_level', label: '等级', labelEn: 'Level' },
      { key: 'common_cards', label: '常交易卡', labelEn: 'Common Cards' },
      { key: 'currency_preferences', label: '币种偏好', labelEn: 'Currency Preferences' },
      { key: 'bank_card', label: '银行卡', labelEn: 'Bank Card' },
      { key: 'customer_feature', label: '客户特点', labelEn: 'Customer Feature' },
      { key: 'source_name', label: '来源', labelEn: 'Source' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'recorder_name', label: '录入人', labelEn: 'Recorder' },
    ],
    importable: true,
    primaryKey: 'phone_number',
  },
  {
    tableName: 'orders',
    displayName: '订单管理',
    displayNameEn: 'Orders',
    columns: [
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'order_number', label: '订单ID', labelEn: 'Order ID' },
      { key: 'order_type', label: '卡片类型', labelEn: 'Card Type' },
      { key: 'card_value', label: '卡片面值', labelEn: 'Card Value' },
      { key: 'exchange_rate', label: '卡片汇率', labelEn: 'Card Rate' },
      { key: 'amount', label: '此卡价值', labelEn: 'Card Worth' },
      { key: 'actual_payment', label: '实付外币', labelEn: 'Actual Payment' },
      { key: 'foreign_rate', label: '外币汇率', labelEn: 'Foreign Rate' },
      { key: 'fee', label: '手续费', labelEn: 'Fee' },
      { key: 'payment_value', label: '代付价值', labelEn: 'Payment Value' },
      { key: 'vendor_id', label: '代付商家', labelEn: 'Payment Provider' },
      { key: 'card_merchant_id', label: '卡商名称', labelEn: 'Card Vendor' },
      { key: 'profit_ngn', label: '本单利润', labelEn: 'Profit' },
      { key: 'profit_rate', label: '本单利率', labelEn: 'Profit Rate' },
      { key: 'phone_number', label: '电话号码', labelEn: 'Phone Number' },
      { key: 'member_code', label: '会员编号', labelEn: 'Member Code' },
      { key: 'currency', label: '需求币种', labelEn: 'Currency' },
      { key: 'creator_name', label: '销售员', labelEn: 'Sales Person' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'status', label: '状态', labelEn: 'Status' },
    ],
    importable: true,
    primaryKey: 'order_number',
  },
  {
    tableName: 'points_ledger',
    displayName: '积分明细',
    displayNameEn: 'Points Ledger',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'member_code', label: '会员编号', labelEn: 'Member Code' },
      { key: 'phone_number', label: '电话号码', labelEn: 'Phone Number' },
      { key: 'order_id', label: '订单ID', labelEn: 'Order ID' },
      { key: 'transaction_type', label: '交易类型', labelEn: 'Transaction Type' },
      { key: 'actual_payment', label: '实付金额', labelEn: 'Actual Payment' },
      { key: 'currency', label: '币种', labelEn: 'Currency' },
      { key: 'exchange_rate', label: '汇率', labelEn: 'Exchange Rate' },
      { key: 'usd_amount', label: 'USD金额', labelEn: 'USD Amount' },
      { key: 'points_multiplier', label: '积分倍率', labelEn: 'Points Multiplier' },
      { key: 'points_earned', label: '获得积分', labelEn: 'Points Earned' },
      { key: 'status', label: '状态', labelEn: 'Status' },
      { key: 'creator_id', label: '创建人ID', labelEn: 'Creator ID' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'member_activity',
    displayName: '会员活动数据',
    displayNameEn: 'Member Activity',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'member_id', label: '会员ID', labelEn: 'Member ID' },
      { key: 'phone_number', label: '电话号码', labelEn: 'Phone Number' },
      { key: 'accumulated_points', label: '累计积分', labelEn: 'Accumulated Points' },
      { key: 'remaining_points', label: '剩余积分', labelEn: 'Remaining Points' },
      { key: 'referral_points', label: '推荐积分', labelEn: 'Referral Points' },
      { key: 'referral_count', label: '推荐人数', labelEn: 'Referral Count' },
      { key: 'total_gift_ngn', label: '赠送NGN', labelEn: 'Total Gift NGN' },
      { key: 'total_gift_ghs', label: '赠送GHS', labelEn: 'Total Gift GHS' },
      { key: 'total_gift_usdt', label: '赠送USDT', labelEn: 'Total Gift USDT' },
      { key: 'last_reset_time', label: '最后重置时间', labelEn: 'Last Reset Time' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'activity_gifts',
    displayName: '活动赠送',
    displayNameEn: 'Activity Gifts',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'member_id', label: '会员ID', labelEn: 'Member ID' },
      { key: 'phone_number', label: '电话号码', labelEn: 'Phone Number' },
      { key: 'currency', label: '币种', labelEn: 'Currency' },
      { key: 'amount', label: '金额', labelEn: 'Amount' },
      { key: 'rate', label: '汇率', labelEn: 'Rate' },
      { key: 'fee', label: '手续费', labelEn: 'Fee' },
      { key: 'gift_value', label: '赠送价值', labelEn: 'Gift Value' },
      { key: 'gift_type', label: '赠送类型', labelEn: 'Gift Type' },
      { key: 'payment_agent', label: '代付商家', labelEn: 'Payment Agent' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'creator_id', label: '创建人ID', labelEn: 'Creator ID' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'referral_relations',
    displayName: '推荐关系',
    displayNameEn: 'Referral Relations',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'referrer_phone', label: '推荐人电话', labelEn: 'Referrer Phone' },
      { key: 'referrer_member_code', label: '推荐人编号', labelEn: 'Referrer Code' },
      { key: 'referee_phone', label: '被推荐人电话', labelEn: 'Referee Phone' },
      { key: 'referee_member_code', label: '被推荐人编号', labelEn: 'Referee Code' },
      { key: 'source', label: '来源', labelEn: 'Source' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'employees',
    displayName: '员工管理',
    displayNameEn: 'Employees',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'username', label: '用户名', labelEn: 'Username' },
      { key: 'real_name', label: '真实姓名', labelEn: 'Real Name' },
      { key: 'role', label: '角色', labelEn: 'Role' },
      { key: 'status', label: '状态', labelEn: 'Status' },
      { key: 'visible', label: '可见', labelEn: 'Visible' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: false,
    primaryKey: 'id',
  },
  {
    tableName: 'cards',
    displayName: '卡片管理',
    displayNameEn: 'Cards',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'type', label: '类型', labelEn: 'Type' },
      { key: 'status', label: '状态', labelEn: 'Status' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'vendors',
    displayName: '卡商管理',
    displayNameEn: 'Vendors',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'status', label: '状态', labelEn: 'Status' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'payment_providers',
    displayName: '代付商家',
    displayNameEn: 'Payment Providers',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'status', label: '状态', labelEn: 'Status' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'customer_sources',
    displayName: '客户来源',
    displayNameEn: 'Customer Sources',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'is_active', label: '是否激活', labelEn: 'Is Active' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'activity_types',
    displayName: '活动类型',
    displayNameEn: 'Activity Types',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'value', label: '值', labelEn: 'Value' },
      { key: 'label', label: '标签', labelEn: 'Label' },
      { key: 'is_active', label: '是否激活', labelEn: 'Is Active' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'currencies',
    displayName: '币种设置',
    displayNameEn: 'Currencies',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'code', label: '代码', labelEn: 'Code' },
      { key: 'name_zh', label: '中文名称', labelEn: 'Chinese Name' },
      { key: 'name_en', label: '英文名称', labelEn: 'English Name' },
      { key: 'symbol', label: '符号', labelEn: 'Symbol' },
      { key: 'is_active', label: '是否激活', labelEn: 'Is Active' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'shift_handovers',
    displayName: '交班记录',
    displayNameEn: 'Shift Handovers',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'handover_employee_id', label: '交班员工ID', labelEn: 'Handover Employee ID' },
      { key: 'handover_employee_name', label: '交班员工', labelEn: 'Handover Employee' },
      { key: 'receiver_name', label: '接班人', labelEn: 'Receiver' },
      { key: 'handover_time', label: '交班时间', labelEn: 'Handover Time' },
      { key: 'remark', label: '备注', labelEn: 'Remark' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'operation_logs',
    displayName: '操作日志',
    displayNameEn: 'Operation Logs',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'timestamp', label: '时间', labelEn: 'Timestamp' },
      { key: 'operator_id', label: '操作员ID', labelEn: 'Operator ID' },
      { key: 'operator_account', label: '操作员账号', labelEn: 'Operator Account' },
      { key: 'operator_role', label: '操作员角色', labelEn: 'Operator Role' },
      { key: 'module', label: '模块', labelEn: 'Module' },
      { key: 'operation_type', label: '操作类型', labelEn: 'Operation Type' },
      { key: 'object_id', label: '对象ID', labelEn: 'Object ID' },
      { key: 'object_description', label: '对象描述', labelEn: 'Object Description' },
      { key: 'is_restored', label: '已恢复', labelEn: 'Is Restored' },
    ],
    importable: false,
    primaryKey: 'id',
  },
  {
    tableName: 'points_accounts',
    displayName: '积分账户',
    displayNameEn: 'Points Accounts',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'member_code', label: '会员编号', labelEn: 'Member Code' },
      { key: 'phone', label: '电话', labelEn: 'Phone' },
      { key: 'current_points', label: '当前积分', labelEn: 'Current Points' },
      { key: 'last_reset_time', label: '最后重置时间', labelEn: 'Last Reset Time' },
      { key: 'points_accrual_start_time', label: '积分累计开始时间', labelEn: 'Accrual Start Time' },
      { key: 'last_updated', label: '最后更新', labelEn: 'Last Updated' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'shared_data_store',
    displayName: '系统设置数据',
    displayNameEn: 'System Settings',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'data_key', label: '键', labelEn: 'Key' },
      { key: 'data_value', label: '值', labelEn: 'Value' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'employee_login_logs',
    displayName: '登录日志',
    displayNameEn: 'Login Logs',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'employee_id', label: '员工ID', labelEn: 'Employee ID' },
      { key: 'login_time', label: '登录时间', labelEn: 'Login Time' },
      { key: 'ip_address', label: 'IP地址', labelEn: 'IP Address' },
      { key: 'user_agent', label: '浏览器信息', labelEn: 'User Agent' },
      { key: 'success', label: '是否成功', labelEn: 'Success' },
      { key: 'failure_reason', label: '失败原因', labelEn: 'Failure Reason' },
      { key: 'login_method', label: '登录方式', labelEn: 'Login Method' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: false,
    primaryKey: 'id',
  },
  {
    tableName: 'knowledge_categories',
    displayName: '知识库分类',
    displayNameEn: 'Knowledge Categories',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'content_type', label: '内容类型', labelEn: 'Content Type' },
      { key: 'is_active', label: '是否激活', labelEn: 'Is Active' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_by', label: '创建人ID', labelEn: 'Created By' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'knowledge_articles',
    displayName: '知识库文章',
    displayNameEn: 'Knowledge Articles',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'category_id', label: '分类ID', labelEn: 'Category ID' },
      { key: 'title_zh', label: '中文标题', labelEn: 'Chinese Title' },
      { key: 'title_en', label: '英文标题', labelEn: 'English Title' },
      { key: 'description', label: '描述', labelEn: 'Description' },
      { key: 'content', label: '内容', labelEn: 'Content' },
      { key: 'image_url', label: '图片URL', labelEn: 'Image URL' },
      { key: 'is_published', label: '是否发布', labelEn: 'Is Published' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_by', label: '创建人ID', labelEn: 'Created By' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'card_types',
    displayName: '卡片类型',
    displayNameEn: 'Card Types',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'audit_records',
    displayName: '审核记录',
    displayNameEn: 'Audit Records',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'target_table', label: '目标表', labelEn: 'Target Table' },
      { key: 'target_id', label: '目标ID', labelEn: 'Target ID' },
      { key: 'action_type', label: '操作类型', labelEn: 'Action Type' },
      { key: 'old_data', label: '旧数据', labelEn: 'Old Data' },
      { key: 'new_data', label: '新数据', labelEn: 'New Data' },
      { key: 'submitter_id', label: '提交人ID', labelEn: 'Submitter ID' },
      { key: 'reviewer_id', label: '审核人ID', labelEn: 'Reviewer ID' },
      { key: 'status', label: '状态', labelEn: 'Status' },
      { key: 'review_comment', label: '审核意见', labelEn: 'Review Comment' },
      { key: 'review_time', label: '审核时间', labelEn: 'Review Time' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
    ],
    importable: false,
    primaryKey: 'id',
  },
  {
    tableName: 'shift_receivers',
    displayName: '接班人列表',
    displayNameEn: 'Shift Receivers',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'name', label: '名称', labelEn: 'Name' },
      { key: 'sort_order', label: '排序', labelEn: 'Sort Order' },
      { key: 'creator_id', label: '创建人ID', labelEn: 'Creator ID' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
  {
    tableName: 'role_permissions',
    displayName: '角色权限',
    displayNameEn: 'Role Permissions',
    columns: [
      { key: 'id', label: 'ID', labelEn: 'ID' },
      { key: 'role', label: '角色', labelEn: 'Role' },
      { key: 'module_name', label: '模块名', labelEn: 'Module Name' },
      { key: 'field_name', label: '字段名', labelEn: 'Field Name' },
      { key: 'can_view', label: '可查看', labelEn: 'Can View' },
      { key: 'can_edit', label: '可编辑', labelEn: 'Can Edit' },
      { key: 'can_delete', label: '可删除', labelEn: 'Can Delete' },
      { key: 'created_at', label: '创建时间', labelEn: 'Created At' },
      { key: 'updated_at', label: '更新时间', labelEn: 'Updated At' },
    ],
    importable: true,
    primaryKey: 'id',
  },
];
