// Re-export bridge — canonical source is @/services/audit/auditLogService
export {
  type OperationType,
  type ModuleType,
  MODULE_NAMES,
  OPERATION_NAMES,
  getModuleName,
  normalizeOperationTypeKey,
  getOperationName,
  RESTORABLE_MODULES,
  type AuditLogEntry,
  initializeAuditLogCache,
  refreshAuditLogCache,
  type AuditLogsPageFilters,
  fetchAuditLogsPage,
  getAuditLogs,
  getLogsByModule,
  getLogsByOperator,
  getLogsByDateRange,
  getLogById,
  appendAuditLog,
  appendAuditLogSync,
  getObjectDiff,
  isRestorableModule,
  markLogAsRestored,
  getCurrentOperator,
  logOperation,
} from '@/services/audit/auditLogService';
