import { useState, useRef } from "react";
import { safeNumber, safeToFixed } from "@/lib/safeCalc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { DrawerDetail } from "@/components/shell/DrawerDetail";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Download, Image as ImageIcon, Loader2, Save } from "lucide-react";
import { notify } from "@/lib/notifyHub";
import { getRateSettingEntries, getPosterTableColumns, type RateSettingEntry, type PosterColumnKey } from "@/services/system/systemSettingsService";
import { useLanguage } from "@/contexts/LanguageContext";
import { useIsMobile } from "@/hooks/use-mobile";
import { useAuth } from "@/contexts/AuthContext";
import { useTenantView } from "@/contexts/TenantViewContext";
import { savePosterToLibrary } from "@/services/taskService";
import { formatBeijingDate, formatBeijingDateLongEnglish } from "@/lib/beijingTime";
import { useMemberResolvableMedia } from "@/hooks/useMemberResolvableMedia";

interface RatePosterGeneratorProps {
  onGenerate?: () => void;
  /** 保存到海报库后的回调（如刷新海报列表） */
  onSavedToLibrary?: () => void;
  /** 汇率配置数据（与海报设置表格一致，不传则从 store 读取） */
  rateEntries?: RateSettingEntry[];
  /** 用于计算兑换金额和百分比（来自海报设置页） */
  getExchangeAmount?: (entry: RateSettingEntry) => string;
  getPercentage?: (entry: RateSettingEntry) => string;
}

type PosterTemplate = "dark" | "light" | "gradient";

interface PosterTextSettings {
  title: string;
  subtitle: string;
  weAlsoBuy: string;
  fundTransfer: string;
  note1: string;
  note2: string;
  footer: string;
}

const DEFAULT_TEXT_SETTINGS: PosterTextSettings = {
  title: "FASTGC Gift Card Company",
  subtitle: "Gift Card Rates (Updated)",
  weAlsoBuy: "Google Korea, PlayStation, XBOX, Amazon, Sephora, VISA Gift Card, Vanilla, Paysafecard",
  fundTransfer: "Chime, PayPal, Cash App, Apple Pay, Venmo, Zelle, Euro Transfer, UK Transfer, Gcash, Western Union, BTC, USDT, Revolut, E-Transfer",
  note1: "• Exchange rates change frequently.",
  note2: "• Please confirm the rate with me before trading.",
  footer: "Generated by FASTGC System",
};

export default function RatePosterGenerator({
  onGenerate,
  onSavedToLibrary,
  rateEntries: rateEntriesProp,
  getExchangeAmount,
  getPercentage,
}: RatePosterGeneratorProps) {
  const { t } = useLanguage();
  const { employee } = useAuth();
  const { viewingTenantId } = useTenantView() || {};
  const isMobile = useIsMobile();
  const [saving, setSaving] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [posterDataUrl, setPosterDataUrl] = useState<string | null>(null);
  const {
    resolvedSrc: posterResolvedSrc,
    usePlaceholder: posterUsePlaceholder,
    onImageError: posterImgError,
  } = useMemberResolvableMedia("rate-poster-preview", posterDataUrl);
  const [selectedTemplate, setSelectedTemplate] = useState<PosterTemplate>("dark");
  const [textSettings, setTextSettings] = useState<PosterTextSettings>(DEFAULT_TEXT_SETTINGS);
  const [showTextEditor, setShowTextEditor] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const getTemplateColors = (template: PosterTemplate) => {
    switch (template) {
      case "dark":
        return {
          bg1: "#1a1a2e",
          bg2: "#16213e",
          bg3: "#0f3460",
          accent: "#FFD700",
          text: "#FFFFFF",
          muted: "#94a3b8",
          warning: "#FF6B6B",
          decorColor: "rgba(255, 215, 0, 0.1)",
        };
      case "light":
        return {
          bg1: "#f8fafc",
          bg2: "#e2e8f0",
          bg3: "#cbd5e1",
          accent: "#1e40af",
          text: "#1e293b",
          muted: "#64748b",
          warning: "#dc2626",
          decorColor: "rgba(30, 64, 175, 0.1)",
        };
      case "gradient":
        return {
          bg1: "#0f172a",
          bg2: "#1e3a5f",
          bg3: "#155e75",
          accent: "#22d3ee",
          text: "#FFFFFF",
          muted: "#94a3b8",
          warning: "#f43f5e",
          decorColor: "rgba(34, 211, 238, 0.15)",
        };
    }
  };

  const generatePoster = async () => {
    setIsGenerating(true);
    
    try {
      const rateEntries = rateEntriesProp && rateEntriesProp.length > 0
        ? rateEntriesProp
        : getRateSettingEntries();
      
      if (rateEntries.length === 0) {
        notify.error(t("没有汇率数据可生成海报", "No rate data to generate poster"));
        setIsGenerating(false);
        return;
      }

      const colors = getTemplateColors(selectedTemplate);

      // Create canvas for poster (1080x1920 - 9:16 ratio)
      const canvas = document.createElement("canvas");
      canvas.width = 1080;
      canvas.height = 1920;
      const ctx = canvas.getContext("2d");
      
      if (!ctx) {
        notify.error(t("无法创建画布", "Cannot create canvas"));
        setIsGenerating(false);
        return;
      }

      // Background gradient
      const gradient = ctx.createLinearGradient(0, 0, 0, 1920);
      gradient.addColorStop(0, colors.bg1);
      gradient.addColorStop(0.5, colors.bg2);
      gradient.addColorStop(1, colors.bg3);
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, 1080, 1920);

      // Add decorative elements
      ctx.fillStyle = colors.decorColor;
      ctx.beginPath();
      ctx.arc(900, 200, 300, 0, Math.PI * 2);
      ctx.fill();
      ctx.beginPath();
      ctx.arc(180, 1700, 250, 0, Math.PI * 2);
      ctx.fill();

      // Header - Main Title
      ctx.fillStyle = colors.accent;
      ctx.font = "bold 56px Arial, sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(textSettings.title, 540, 120);

      // Subtitle
      ctx.fillStyle = colors.text;
      ctx.font = "32px Arial, sans-serif";
      ctx.fillText(textSettings.subtitle, 540, 180);

      // Current date
      ctx.fillStyle = colors.muted;
      ctx.font = "24px Arial, sans-serif";
      const today = formatBeijingDateLongEnglish(new Date());
      ctx.fillText(today, 540, 220);

      // Table configuration - 按海报设置页的列配置动态生成
      const visibleColumns = getPosterTableColumns();
      if (visibleColumns.length === 0) {
        notify.error(t("请至少勾选一列用于海报表格", "Please select at least one column for the poster table"));
        setIsGenerating(false);
        return;
      }

      const columnLabels: Record<PosterColumnKey, string> = {
        country: "Country",
        card: "Card",
        faceValue: "Face Value",
        exchangeAmount: "Exchange Amt",
        currency: "Currency",
        percentageRate: "Pct(%)",
        rate: "Rate",
        profitRate: "Profit(%)",
      };

      const tableTop = 280;
      const tableLeft = 40;
      const tableWidth = 1000;
      const headerHeight = 60;
      const rowHeight = 50;
      const colCount = visibleColumns.length;
      const colWidth = tableWidth / colCount;
      const colWidths = visibleColumns.map(() => colWidth);

      // Draw table header background
      ctx.fillStyle = colors.accent;
      ctx.fillRect(tableLeft, tableTop, tableWidth, headerHeight);

      // Draw header text - 列多时缩小字体
      ctx.fillStyle = selectedTemplate === "light" ? "#FFFFFF" : colors.bg1;
      const headerFontSize = colCount > 6 ? 18 : 24;
      ctx.font = `bold ${headerFontSize}px Arial, sans-serif`;
      ctx.textAlign = "center";
      
      let xPos = tableLeft;
      visibleColumns.forEach((key, i) => {
        const header = columnLabels[key];
        ctx.fillText(header, xPos + colWidths[i] / 2, tableTop + 40);
        xPos += colWidths[i];
      });

      // Draw table rows
      const maxRows = Math.min(rateEntries.length, 20); // Limit rows to fit
      
      const getCardEnglishPart = (card: string | number): string => {
        if (!card) return "-";
        let s = String(card);
        s = s.replace(/\s*[（(][^）)]*[）)]\s*/g, "").trim();
        s = s.replace(/[\u4e00-\u9fff\u3000-\u303f\uff00-\uffef]/g, "").trim();
        return s || "-";
      };
      const getCellValue = (entry: RateSettingEntry, key: PosterColumnKey): string => {
        switch (key) {
          case "country": return entry.country || "-";
          case "card": return getCardEnglishPart(entry.card || "");
          case "faceValue": return `$${safeNumber(entry.faceValue)}`;
          case "exchangeAmount":
            if (getExchangeAmount) return getExchangeAmount(entry);
            return entry.exchangeAmount != null ? safeToFixed(entry.exchangeAmount, 2) : "-";
          case "currency": return entry.currency;
          case "percentageRate": {
            if (!entry.faceValue || !entry.rate) return "-";
            if (getPercentage) return getPercentage(entry);
            if (entry.percentageRate != null) return `${Math.round(entry.percentageRate)}%`;
            return "-";
          }
          case "rate": return entry.rate != null ? safeToFixed(entry.rate, 2) : "-";
          case "profitRate": return entry.profitRate != null ? `${safeToFixed(entry.profitRate, 1)}%` : "-";
          default: return "-";
        }
      };

      for (let i = 0; i < maxRows; i++) {
        const entry = rateEntries[i];
        const rowY = tableTop + headerHeight + i * rowHeight;
        
        // Alternating row colors
        ctx.fillStyle = i % 2 === 0 ? "rgba(255, 255, 255, 0.1)" : "rgba(255, 255, 255, 0.05)";
        ctx.fillRect(tableLeft, rowY, tableWidth, rowHeight);

        // Draw row data - 列多时缩小字体避免溢出
        ctx.fillStyle = colors.text;
        const rowFontSize = colCount > 6 ? 16 : 20;
        ctx.font = `${rowFontSize}px Arial, sans-serif`;
        ctx.textAlign = "center";

        xPos = tableLeft;
        visibleColumns.forEach((key, j) => {
          const cellVal = getCellValue(entry, key);
          ctx.fillText(cellVal, xPos + colWidths[j] / 2, rowY + 33);
          xPos += colWidths[j];
        });
      }

      // Draw table border
      ctx.strokeStyle = colors.accent;
      ctx.lineWidth = 2;
      ctx.strokeRect(tableLeft, tableTop, tableWidth, headerHeight + maxRows * rowHeight);

      // Bottom section - Services
      const bottomY = tableTop + headerHeight + maxRows * rowHeight + 60;
      
      // "We Also Buy" section
      ctx.fillStyle = colors.accent;
      ctx.font = "bold 28px Arial, sans-serif";
      ctx.textAlign = "left";
      ctx.fillText("❤️ We Also Buy:", tableLeft, bottomY);

      ctx.fillStyle = colors.text;
      ctx.font = "22px Arial, sans-serif";
      wrapText(ctx, textSettings.weAlsoBuy, tableLeft, bottomY + 40, tableWidth, 30);

      // "Fund Transfer Services" section
      ctx.fillStyle = colors.accent;
      ctx.font = "bold 28px Arial, sans-serif";
      ctx.fillText("❤️ Fund Transfer Services:", tableLeft, bottomY + 120);

      ctx.fillStyle = colors.text;
      ctx.font = "22px Arial, sans-serif";
      wrapText(ctx, textSettings.fundTransfer, tableLeft, bottomY + 160, tableWidth, 30);

      // Note section
      ctx.fillStyle = colors.warning;
      ctx.font = "bold 28px Arial, sans-serif";
      ctx.fillText("❗ Note:", tableLeft, bottomY + 280);

      ctx.fillStyle = colors.text;
      ctx.font = "22px Arial, sans-serif";
      ctx.fillText(textSettings.note1, tableLeft + 20, bottomY + 320);
      ctx.fillText(textSettings.note2, tableLeft + 20, bottomY + 355);

      // Footer
      ctx.fillStyle = colors.muted;
      ctx.font = "20px Arial, sans-serif";
      ctx.textAlign = "center";
      ctx.fillText(textSettings.footer, 540, 1880);

      let dataUrl = "";
      try {
        dataUrl = canvas.toDataURL("image/webp", 0.92);
      } catch {
        /* ignore */
      }
      if (!dataUrl.startsWith("data:image/webp")) {
        dataUrl = canvas.toDataURL("image/jpeg", 0.92);
      }
      setPosterDataUrl(dataUrl);
      
      onGenerate?.();
      notify.success(t("海报生成成功", "Poster generated successfully"));
    } catch (error) {
      console.error("Error generating poster:", error);
      notify.error(t("海报生成失败", "Failed to generate poster"));
    } finally {
      setIsGenerating(false);
    }
  };

  // Helper function to wrap text
  const wrapText = (
    ctx: CanvasRenderingContext2D,
    text: string,
    x: number,
    y: number,
    maxWidth: number,
    lineHeight: number
  ) => {
    const words = text.split(", ");
    let line = "";
    let currentY = y;

    for (let i = 0; i < words.length; i++) {
      const testLine = line + (line ? ", " : "") + words[i];
      const metrics = ctx.measureText(testLine);
      
      if (metrics.width > maxWidth && line) {
        ctx.fillText(line + ",", x, currentY);
        line = words[i];
        currentY += lineHeight;
      } else {
        line = testLine;
      }
    }
    ctx.fillText(line, x, currentY);
  };

  const downloadPoster = () => {
    if (!posterDataUrl) return;
    
    const link = document.createElement("a");
    link.download = `FASTGC_Rates_${selectedTemplate}_${new Date().toISOString().split("T")[0]}.jpg`;
    link.href = posterDataUrl;
    link.click();
    
    notify.success(t("海报下载成功", "Poster downloaded successfully"));
  };

  const saveToLibrary = async () => {
    const tenantId = viewingTenantId || employee?.tenant_id;
    if (!posterDataUrl || !employee?.id || !tenantId) {
      notify.error(t("请先登录", "Please login"));
      return;
    }
    setSaving(true);
    try {
      const timeoutMs = 30_000;
      const savePromise = savePosterToLibrary({
        tenantId,
        employeeId: employee.id,
        dataUrl: posterDataUrl,
        title: `${t("汇率海报", "Rate Poster")} ${formatBeijingDate(new Date())}`,
      });
      const timeoutPromise = new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error("TIMEOUT")), timeoutMs),
      );
      await Promise.race([savePromise, timeoutPromise]);
      notify.success(t("已保存到海报库", "Saved to poster library"));
      onSavedToLibrary?.();
    } catch (e: any) {
      console.error("Save poster to library failed:", e);
      if (e?.message === "TIMEOUT") {
        notify.error(t("保存超时，请检查网络后重试", "Save timed out, please check network and retry"));
      } else if (e?.statusCode === 413 || e?.message?.includes("too large")) {
        notify.error(t("海报文件过大，请减少表格行数后重试", "Poster too large, reduce rows and retry"));
      } else {
        const msg = e?.message || t("保存失败，请重试", "Save failed, please retry");
        notify.error(msg);
      }
    } finally {
      setSaving(false);
    }
  };

  const handleOpenDialog = () => {
    setIsDialogOpen(true);
    setPosterDataUrl(null);
    setShowTextEditor(false);
  };

  const templateLabels: Record<PosterTemplate, string> = {
    dark: t("深色模板", "Dark Template"),
    light: t("浅色模板", "Light Template"),
    gradient: t("渐变模板", "Gradient Template"),
  };

  return (
    <>
      <Button onClick={handleOpenDialog} className="gap-2">
        <ImageIcon className="h-4 w-4" />
        {t("生成海报", "Generate Poster")}
      </Button>

      <DrawerDetail
        open={isDialogOpen}
        onOpenChange={setIsDialogOpen}
        title={t("生成汇率海报", "Generate Rate Poster")}
        sheetMaxWidth="3xl"
      >
          <div className="space-y-4">
            {/* Template Selection */}
            <div className={`${isMobile ? 'flex flex-col gap-2' : 'flex items-center gap-4'}`}>
              <Label className={isMobile ? '' : 'w-20'}>{t("模板", "Template")}</Label>
              <Select value={selectedTemplate} onValueChange={(v) => setSelectedTemplate(v as PosterTemplate)}>
                <SelectTrigger className={isMobile ? 'w-full' : 'w-48'}>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="dark">{templateLabels.dark}</SelectItem>
                  <SelectItem value="light">{templateLabels.light}</SelectItem>
                  <SelectItem value="gradient">{templateLabels.gradient}</SelectItem>
                </SelectContent>
              </Select>
              <Button 
                variant="outline" 
                size="sm"
                onClick={() => setShowTextEditor(!showTextEditor)}
                className={isMobile ? 'w-full' : ''}
              >
                {showTextEditor ? t("隐藏文字编辑", "Hide Text Editor") : t("编辑文字内容", "Edit Text Content")}
              </Button>
            </div>

            {/* Text Editor */}
            {showTextEditor && (
              <div className="space-y-3 p-4 bg-muted/30 rounded-lg">
              <div className={`grid ${isMobile ? 'grid-cols-1' : 'grid-cols-2'} gap-3`}>
                  <div>
                    <Label className="text-xs">{t("标题", "Title")}</Label>
                    <Input
                      value={textSettings.title}
                      onChange={(e) => setTextSettings(prev => ({ ...prev, title: e.target.value }))}
                      className="h-8 text-sm"
                    />
                  </div>
                  <div>
                    <Label className="text-xs">{t("副标题", "Subtitle")}</Label>
                    <Input
                      value={textSettings.subtitle}
                      onChange={(e) => setTextSettings(prev => ({ ...prev, subtitle: e.target.value }))}
                      className="h-8 text-sm"
                    />
                  </div>
                </div>
                <div>
                  <Label className="text-xs">{t("我们还收购", "We Also Buy")}</Label>
                  <Textarea
                    value={textSettings.weAlsoBuy}
                    onChange={(e) => setTextSettings(prev => ({ ...prev, weAlsoBuy: e.target.value }))}
                    rows={2}
                    className="text-sm"
                  />
                </div>
                <div>
                  <Label className="text-xs">{t("资金转账服务", "Fund Transfer Services")}</Label>
                  <Textarea
                    value={textSettings.fundTransfer}
                    onChange={(e) => setTextSettings(prev => ({ ...prev, fundTransfer: e.target.value }))}
                    rows={2}
                    className="text-sm"
                  />
                </div>
                <div className={`grid ${isMobile ? 'grid-cols-1' : 'grid-cols-2'} gap-3`}>
                  <div>
                    <Label className="text-xs">{t("注意事项1", "Note 1")}</Label>
                    <Input
                      value={textSettings.note1}
                      onChange={(e) => setTextSettings(prev => ({ ...prev, note1: e.target.value }))}
                      className="h-8 text-sm"
                    />
                  </div>
                  <div>
                    <Label className="text-xs">{t("注意事项2", "Note 2")}</Label>
                    <Input
                      value={textSettings.note2}
                      onChange={(e) => setTextSettings(prev => ({ ...prev, note2: e.target.value }))}
                      className="h-8 text-sm"
                    />
                  </div>
                </div>
                <div>
                  <Label className="text-xs">{t("底部文字", "Footer")}</Label>
                  <Input
                    value={textSettings.footer}
                    onChange={(e) => setTextSettings(prev => ({ ...prev, footer: e.target.value }))}
                    className="h-8 text-sm"
                  />
                </div>
                <Button 
                  variant="ghost" 
                  size="sm"
                  onClick={() => setTextSettings(DEFAULT_TEXT_SETTINGS)}
                >
                  {t("重置为默认", "Reset to Default")}
                </Button>
              </div>
            )}

            {!posterDataUrl ? (
              <div className="text-center py-8 space-y-4">
                <div className="text-muted-foreground">
                  {t(
                    "点击下方按钮生成包含最新汇率数据的9:16海报图片（1080×1920像素）",
                    "Click the button below to generate a 9:16 poster image (1080×1920 pixels) with the latest rate data"
                  )}
                </div>
                <div className="text-xs text-muted-foreground">
                  {t(
                    "表格列由海报设置页的「海报表格列」勾选决定，勾选哪些就显示哪些",
                    "Table columns are determined by the poster settings - checked columns will be shown"
                  )}
                </div>
                <Button 
                  onClick={generatePoster} 
                  disabled={isGenerating}
                  size="lg"
                  className="gap-2"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      {t("生成中...", "Generating...")}
                    </>
                  ) : (
                    <>
                      <ImageIcon className="h-4 w-4" />
                      {t("生成海报", "Generate Poster")}
                    </>
                  )}
                </Button>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="flex justify-center">
                  {posterUsePlaceholder ? (
                    <div className="max-h-[500px] min-h-[200px] w-full max-w-md rounded-lg border bg-muted/50 flex items-center justify-center shadow-lg">
                      <ImageIcon className="h-14 w-14 text-muted-foreground/35" aria-hidden />
                    </div>
                  ) : (
                    <img
                      src={posterResolvedSrc}
                      alt="Generated Poster"
                      className="max-h-[500px] rounded-lg shadow-lg border"
                      onError={posterImgError}
                    />
                  )}
                </div>
                <div className="flex justify-center gap-3 flex-wrap">
                  <Button variant="outline" onClick={generatePoster} disabled={isGenerating}>
                    {isGenerating ? (
                      <Loader2 className="h-4 w-4 animate-spin mr-2" />
                    ) : null}
                    {t("重新生成", "Regenerate")}
                  </Button>
                  <Button onClick={downloadPoster} className="gap-2">
                    <Download className="h-4 w-4" />
                    {t("下载海报", "Download Poster")}
                  </Button>
                  <Button variant="outline" onClick={saveToLibrary} disabled={saving} className="gap-2">
                    {saving ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Save className="h-4 w-4" />
                    )}
                    {t("保存到海报库", "Save to Library")}
                  </Button>
                </div>
              </div>
            )}
          </div>

          <div className="flex flex-wrap justify-end gap-2 pt-4 mt-4 border-t border-border">
            <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
              {t("关闭", "Close")}
            </Button>
          </div>
      </DrawerDetail>
    </>
  );
}
