// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// 检测是否为占位符或无效配置（避免 createClient 因无效 URL 抛错导致白屏）
function isValidSupabaseConfig(url: string | undefined, key: string | undefined): boolean {
  if (!url || !key || typeof url !== 'string' || typeof key !== 'string') return false;
  if (url.includes('your_supabase') || url.includes('your_project') || key.includes('your_') || key === 'placeholder-key') return false;
  try {
    const u = new URL(url);
    return u.protocol === 'https:' && u.hostname.endsWith('.supabase.co');
  } catch {
    return false;
  }
}

const effectiveUrl = isValidSupabaseConfig(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  ? SUPABASE_URL!
  : 'https://placeholder.supabase.co'; // 占位 URL，避免 createClient 抛错；请求会失败但页面可渲染
const effectiveKey = isValidSupabaseConfig(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  ? SUPABASE_PUBLISHABLE_KEY!
  : 'placeholder-key';

// 供 UI 判断是否已正确配置 Supabase（未配置时登录会失败，但页面可正常渲染）
export const isSupabaseConfigured = isValidSupabaseConfig(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(effectiveUrl, effectiveKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});